AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam-app

  Sample SAM Template for sam-app

  '
Metadata:
  AWS::ServerlessRepo::Application:
    Name: python-gqt
    Description: python gqt application
    Author: Ryan Layer
    SpdxLicenseId: Apache-2.0
    HomePageUrl: https://github.com/gqt
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/gqt
Globals:
  Function:
    Timeout: 3
Resources:
  GQT:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.handler
      Runtime: python2.7
      CodeUri: s3://layer-overflow-bucket/a3e01a545145499af62051f909dec581
